// <auto-generated />
namespace WebServSendMail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtablewssm_sendMail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablewssm_sendMail));
        
        string IMigrationMetadata.Id
        {
            get { return "201906031907207_add table wssm_sendMail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
